### ISSUE TITLE
TS Multiple successive .extend

### ISSUE THREAD

**Issue by kukinsula** [fastify/fluent-json-schema#108]
## 💥 Regression Report

I am unable to compile my TS fluent schemas with two successive .extend.

## Last working version

Worked up to version: 1.0.4
Stopped working in version: 2.0.3

## To Reproduce

```ts
import S from 'fluent-json-schema';

export const BaseSchema = S
  .object()
  .additionalProperties(false)
  .title('Base Schema')
  .description('Base')
  .id('base')
  .prop('baseProp', S.string());

export const ChildrenSchema = S
  .object()
  .additionalProperties(false)
  .title('Children Schema')
  .description('Children')
  .id('children')
  .prop('childrenProp', S.string())
  .extend(BaseSchema);

export const GrandChildrenSchema = S
  .object()
  .additionalProperties(false)
  .title('Grand Children Schema')
  .description('Grand Children')
  .id('grandChildren')
  .prop('grandChildrenProp', S.string())
  .extend(ChildrenSchema);                     // Error
  // .extend(BaseSchema)                       // Works
```

## Expected behavior

I was expecting to be able to extend successively fluent schemas.

It made me wonder if this is possible to extend schemas this way. If not, how do you recommend to do this ?

```ts
error TS2345: Argument of type 'Pick<ObjectSchema, "isFluentSchema" | "extend">' is not assignable to parameter of type 'ObjectSchema'.
  Type 'Pick<ObjectSchema, "isFluentSchema" | "extend">' is missing the following properties from type 'ObjectSchema': definition, prop, additionalProperties, maxProperties, and 24 more.

.extend(ChildrenSchema); // Error
```

## Your Environment

- *node version*: 15.8.0
- *fastify version*: 3.12.0
- *os*: Linux

**Comment by climba03003** [comment]
The major problem is `ObjectSchema` is not compatible with `ExtendedSchema`.
You can `.extend` multiple `ObjectSchema` but not a single `ExtendedSchema`.

Anyway, this is the bug I introduced for fixing the types in #80 which is `1.0.5`.
I will fix it with #109.
